// Code generated by "stringer -type Route -linecomment"; DO NOT EDIT.

package routes

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[One-1]
	_ = x[Two-2]
	_ = x[Three-3]
	_ = x[Four-4]
	_ = x[Five-5]
	_ = x[Six-6]
	_ = x[Seven-7]
	_ = x[A-8]
	_ = x[B-9]
	_ = x[C-10]
	_ = x[D-11]
	_ = x[E-12]
	_ = x[F-13]
	_ = x[G-14]
	_ = x[J-15]
	_ = x[L-16]
	_ = x[M-17]
	_ = x[N-18]
	_ = x[Q-19]
	_ = x[R-20]
	_ = x[S-21]
	_ = x[SIR-22]
	_ = x[W-23]
	_ = x[Z-24]
}

const _Route_name = "Unknown1234567ABCDEFGJLMNQRSSIRWZ"

var _Route_index = [...]uint8{0, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 31, 32, 33}

func (i Route) String() string {
	if i >= Route(len(_Route_index)-1) {
		return "Route(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Route_name[_Route_index[i]:_Route_index[i+1]]
}
