// Code generated by "stringer -type Borough -linecomment"; DO NOT EDIT.

package boroughs

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Manhattan-1]
	_ = x[Brooklyn-2]
	_ = x[Bronx-3]
	_ = x[Queens-4]
	_ = x[StatenIsland-5]
}

const _Borough_name = "UnknownManhattanBrooklynBronxQueensStaten Island"

var _Borough_index = [...]uint8{0, 7, 16, 24, 29, 35, 48}

func (i Borough) String() string {
	if i >= Borough(len(_Borough_index)-1) {
		return "Borough(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Borough_name[_Borough_index[i]:_Borough_index[i+1]]
}
