// Code generated by "stringer -type Division -linecomment"; DO NOT EDIT.

package division

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DivisionBMT-0]
	_ = x[DivisionIND-1]
	_ = x[DivisionIRT-2]
	_ = x[DivisionSIR-3]
	_ = x[UnknownDivision-4]
}

const _Division_name = "BMTINDIRTSIRunknown"

var _Division_index = [...]uint8{0, 3, 6, 9, 12, 19}

func (i Division) String() string {
	if i >= Division(len(_Division_index)-1) {
		return "Division(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Division_name[_Division_index[i]:_Division_index[i+1]]
}
