// Code generated by "stringer -type Structure -linecomment"; DO NOT EDIT.

package structure

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StructureAtGrade-0]
	_ = x[StructureElevated-1]
	_ = x[StructureEmbankment-2]
	_ = x[StructureOpenCut-3]
	_ = x[StructureSubway-4]
	_ = x[StructureViaduct-5]
	_ = x[UnknownStructure-6]
}

const _Structure_name = "At GradeElevatedEmbankmentOpen CutSubwayViaductUnknown"

var _Structure_index = [...]uint8{0, 8, 16, 26, 34, 40, 47, 54}

func (i Structure) String() string {
	if i >= Structure(len(_Structure_index)-1) {
		return "Structure(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Structure_name[_Structure_index[i]:_Structure_index[i+1]]
}
