// Code generated by "stringer -type ApiMethod -linecomment"; DO NOT EDIT.

package apimethods

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GetStation-0]
	_ = x[GetStations-1]
	_ = x[GetUpcomingTrains-2]
	_ = x[GetStationComplex-3]
	_ = x[GetStationComplexes-4]
	_ = x[GetAllRoutes-5]
	_ = x[GetAllBoroughs-6]
	_ = x[GetAllDivisions-7]
	_ = x[GetAllStructures-8]
}

const _ApiMethod_name = "GetStationGetStationsGetUpcomingTrainsGetStationComplexGetStationComplexesGetAllRoutesGetAllBoroughsGetAllDivisionsGetAllStructures"

var _ApiMethod_index = [...]uint8{0, 10, 21, 38, 55, 74, 86, 100, 115, 131}

func (i ApiMethod) String() string {
	if i >= ApiMethod(len(_ApiMethod_index)-1) {
		return "ApiMethod(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ApiMethod_name[_ApiMethod_index[i]:_ApiMethod_index[i+1]]
}
