// Code generated by "stringer -type Borough -linecomment"; DO NOT EDIT.

package borough

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Manhattan-0]
	_ = x[Brooklyn-1]
	_ = x[Bronx-2]
	_ = x[Queens-3]
	_ = x[StatenIsland-4]
	_ = x[UnknownBorough-5]
}

const _Borough_name = "ManhattanBrooklynBronxQueensStaten IslandUnknown"

var _Borough_index = [...]uint8{0, 9, 17, 22, 28, 41, 48}

func (i Borough) String() string {
	if i >= Borough(len(_Borough_index)-1) {
		return "Borough(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Borough_name[_Borough_index[i]:_Borough_index[i+1]]
}
