version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "sriracha"
      POSTGRES_PASSWORD: "salty1234"
      POSTGRES_DB: "mtadata"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"